package space.lopatkin.spb.helpboardgamecard.domain.model

enum class Message {

    POOL_EMPTY, ACTION_ENDED_ERROR, ACTION_ENDED_SUCCESS, ACTION_STOPPED,

    DELETE_ITEM_ACTION_ENDED_ERROR, DELETE_ITEM_ACTION_ENDED_SUCCESS, DELETE_ITEM_ACTION_STOPPED,

    FAVORITE_ITEM_ACTION_ENDED_ERROR, FAVORITE_ITEM_ACTION_ENDED_SUCCESS, FAVORITE_ITEM_ACTION_STOPPED,

    LOCKING_ITEM_ACTION_ENDED_ERROR, LOCKING_ITEM_ACTION_ENDED_SUCCESS, LOCKING_ITEM_ACTION_STOPPED

}
